sonar.projectKey=md-sadidtahsin_cap-test
sonar.organization=md-sadidtahsin
sonar.host.url=https://sonarcloud.io
# sonar.sources=node-service,python-service,go-service
sonar.sources=node-service,python-service
# sonar.tests=node-service,python-service,go-service
sonar.tests=node-service,python-service
sonar.test.inclusions=**/*_test.go,**/__tests__/**,tests/**
sonar.exclusions=**/coverage.out,**/coverage/**,**/Dockerfile,node-service/__tests__/**,node-service/coverage/**,python-service/tests/**,python-service/coverage/**,python-service/templates/**,python-service/**/__pycache__/**,python-service/**/.pytest_cache/**
sonar.coverage.exclusions=**/*_test.go
sonar.javascript.lcov.reportPaths=node-service/coverage/lcov.info
sonar.python.coverage.reportPaths=python-service/coverage/coverage.xml
# sonar.go.coverage.reportPaths=go-service/coverage.out
