apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: urlshortener
type: Opaque
stringData:
  DOCKERHUB_USERNAME: "your-username"
  DOCKERHUB_TOKEN: "your-token"
  SONAR_TOKEN: "your-sonarcloud-token"