sonar.projectKey=md-sadidtahsin_cap-test
sonar.organization=md-sadidtahsin
sonar.sources=go-service
sonar.exclusions=**/*_test.go,**/coverage.out,go-service/Dockerfile
sonar.host.url=https://sonarcloud.io
sonar.go.coverage.reportPaths=go-service/coverage.out
