sonar.projectKey=md-sadidtahsin_cap-test
sonar.organization=md-sadidtahsin
sonar.sources=.
sonar.tests=__tests__
sonar.exclusions=__tests__/**,coverage/**
sonar.host.url=https://sonarcloud.io
sonar.javascript.lcov.reportPaths=coverage/lcov.info
